version: '3.8'

services:

  event-db:
    extends:
      file: gradleProject/eventService/docker-compose.yml
      service: event-db

  event-service:
    extends:
      file: gradleProject/eventservice/docker-compose.yml
      service: event-service

  web-server:
    extends:
      file: webserver/docker-compose.yml
      service: web-server

volumes:
  event-volume:

networks:
  backend:
    driver: bridge
