version: '3.8'

services:

  event-db:
    image: mariadb:10.5.12
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventdb
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: event-volume
        target: /var/lib/mysql
    networks:
      - backend

  event-service:
    build: ./gradleProject/eventService/
    ports:
      - "49160:8080"
    depends_on:
      - event-db
    networks:
      - backend

  web-server:
    build: ./webserver/
    ports:
      - "8080:8080"
    depends_on:
      - event-service
    networks:
      - backend

volumes:
  event-volume:

networks:
  backend:
    driver: bridge
